// document.addEventListener("DOMContentLoaded", function () {
//   setInterval(() => {
//     // Home
//     updateAGVPosition();

//     updatePositionResult();
//     updaterowTitle();
//     updateStepDropdown();
//     updateCurrentStep();
//     //header
//     updateHeaderStatus();
//     //alarms
//     createAlarmsTable();
//     //wms
//     updateWMSScreen();
//     updateErrorTooltip();
//     //position and machine
//     updateAGVPositionHMI_mm(CarrierActualPosition_mm);
//     //machine
//     updateSensorsFromBits();
//     //sidebar
//  //   updateSpeedLabels();
//     // updateStatusModeFromstring();
//   //  console.log(decodeHTMLEntity(newGData.Array_1));
//     //Test
//     // setInterval(() => {
//     //   Test();
//     // }, 1000); // Update rate
//   }, 1000); // Update rate
// });
